/**
 * AVRORA: Chart Artifact Display Component
 *
 * Renders various chart types generated by AI
 * Supports: line charts, bar charts, pie charts, area charts
 */

"use client";

import { motion } from "framer-motion";
import { BarChart3, Download, Sparkles } from "lucide-react";
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Legend,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { cn } from "@/lib/utils";

type ChartData = {
  [key: string]: string | number;
};

type ChartArtifactProps = {
  chartType: "line" | "bar" | "pie" | "area";
  data: ChartData[];
  title?: string;
  xKey?: string;
  yKey?: string;
  colors?: string[];
  className?: string;
};

const DEFAULT_COLORS = [
  "#3b82f6", // blue
  "#8b5cf6", // purple
  "#ec4899", // pink
  "#10b981", // green
  "#f59e0b", // amber
  "#ef4444", // red
  "#06b6d4", // cyan
  "#f97316", // orange
];

export function ChartArtifact({
  chartType,
  data,
  title,
  xKey = "name",
  yKey = "value",
  colors = DEFAULT_COLORS,
  className,
}: ChartArtifactProps) {
  const handleDownload = () => {
    // Download chart data as CSV
    const csv = [
      Object.keys(data[0]).join(","),
      ...data.map((row) => Object.values(row).join(",")),
    ].join("\n");

    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `chart-${Date.now()}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const renderChart = () => {
    switch (chartType) {
      case "line":
        return (
          <ResponsiveContainer height={300} width="100%">
            <LineChart data={data}>
              <CartesianGrid stroke="#e5e7eb" strokeDasharray="3 3" />
              <XAxis dataKey={xKey} stroke="#6b7280" />
              <YAxis stroke="#6b7280" />
              <Tooltip
                contentStyle={{
                  backgroundColor: "#fff",
                  border: "1px solid #e5e7eb",
                  borderRadius: "0.5rem",
                }}
              />
              <Legend />
              <Line
                activeDot={{ r: 6 }}
                dataKey={yKey}
                dot={{ fill: colors[0], r: 4 }}
                stroke={colors[0]}
                strokeWidth={2}
                type="monotone"
              />
            </LineChart>
          </ResponsiveContainer>
        );

      case "bar":
        return (
          <ResponsiveContainer height={300} width="100%">
            <BarChart data={data}>
              <CartesianGrid stroke="#e5e7eb" strokeDasharray="3 3" />
              <XAxis dataKey={xKey} stroke="#6b7280" />
              <YAxis stroke="#6b7280" />
              <Tooltip
                contentStyle={{
                  backgroundColor: "#fff",
                  border: "1px solid #e5e7eb",
                  borderRadius: "0.5rem",
                }}
              />
              <Legend />
              <Bar dataKey={yKey} radius={[8, 8, 0, 0]}>
                {data.map((item, index) => {
                  const uniqueKey = item[xKey] ?? `cell-${index}`;
                  return (
                    <Cell
                      fill={colors[index % colors.length]}
                      key={String(uniqueKey)}
                    />
                  );
                })}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        );

      case "pie":
        return (
          <ResponsiveContainer height={300} width="100%">
            <PieChart>
              <Pie
                cx="50%"
                cy="50%"
                data={data}
                dataKey={yKey}
                label
                nameKey={xKey}
                outerRadius={100}
              >
                {data.map((item, index) => {
                  const uniqueKey = item[xKey] ?? `cell-${index}`;
                  return (
                    <Cell
                      fill={colors[index % colors.length]}
                      key={String(uniqueKey)}
                    />
                  );
                })}
              </Pie>
              <Tooltip
                contentStyle={{
                  backgroundColor: "#fff",
                  border: "1px solid #e5e7eb",
                  borderRadius: "0.5rem",
                }}
              />
              <Legend />
            </PieChart>
          </ResponsiveContainer>
        );

      case "area":
        return (
          <ResponsiveContainer height={300} width="100%">
            <AreaChart data={data}>
              <CartesianGrid stroke="#e5e7eb" strokeDasharray="3 3" />
              <XAxis dataKey={xKey} stroke="#6b7280" />
              <YAxis stroke="#6b7280" />
              <Tooltip
                contentStyle={{
                  backgroundColor: "#fff",
                  border: "1px solid #e5e7eb",
                  borderRadius: "0.5rem",
                }}
              />
              <Legend />
              <Area
                dataKey={yKey}
                fill={colors[0]}
                fillOpacity={0.3}
                stroke={colors[0]}
                type="monotone"
              />
            </AreaChart>
          </ResponsiveContainer>
        );

      default:
        return <div>Unsupported chart type</div>;
    }
  };

  return (
    <motion.div
      animate={{ opacity: 1, y: 0 }}
      className={cn(
        "rounded-lg border bg-gradient-to-br from-emerald-50 to-teal-50 p-4 shadow-sm",
        className
      )}
      initial={{ opacity: 0, y: 20 }}
      transition={{ duration: 0.3 }}
    >
      {/* Header */}
      <div className="mb-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="rounded-full bg-emerald-100 p-2">
            <BarChart3 className="h-5 w-5 text-emerald-600" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="font-medium text-emerald-900">
                {title || "Generated Chart"}
              </h3>
              <Sparkles className="h-4 w-4 text-emerald-600" />
            </div>
            <p className="text-emerald-700 text-xs capitalize">
              {chartType} Chart
            </p>
          </div>
        </div>
        <button
          className="rounded-md bg-emerald-600 p-2 text-white transition-colors hover:bg-emerald-700"
          onClick={handleDownload}
          title="Download data as CSV"
          type="button"
        >
          <Download className="h-4 w-4" />
        </button>
      </div>

      {/* Chart */}
      <div className="rounded-lg bg-white p-4">{renderChart()}</div>
    </motion.div>
  );
}
