/**
 * AVRORA: Mini-App Artifact Display Component
 *
 * Renders mini-app specifications generated by AI
 * Version 2: Shows the React component with preview and code display
 */

"use client";

import { motion } from "framer-motion";
import { AppWindow, CheckCircle2, Code2, Copy, Sparkles } from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils";

type LayoutItem = {
  id: string;
  type: string;
  text?: string;
  name?: string;
};

type MiniAppArtifactProps = {
  id: string;
  title: string;
  purpose: string;
  features: string[];
  layout?: LayoutItem[];
  reactCode?: string;
  componentInfo?: {
    name: string;
    imports: string[];
    dependencies: Record<string, string>;
    hasState: boolean;
    hasEffects: boolean;
  };
  specVersion?: number;
  className?: string;
};

export function MiniAppArtifact({
  id,
  title,
  purpose,
  features,
  layout,
  reactCode,
  componentInfo,
  specVersion = 2,
  className,
}: MiniAppArtifactProps) {
  const [showCode, setShowCode] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleCopyCode = () => {
    if (reactCode) {
      navigator.clipboard.writeText(reactCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <motion.div
      animate={{ opacity: 1, y: 0 }}
      className={cn(
        "overflow-hidden rounded-lg border bg-gradient-to-br from-violet-50 to-purple-50 shadow-sm",
        className
      )}
      initial={{ opacity: 0, y: 20 }}
      transition={{ duration: 0.3 }}
    >
      {/* Header */}
      <div className="border-b bg-gradient-to-r from-violet-100 to-purple-100 p-4">
        <div className="flex items-center gap-3">
          <div className="rounded-full bg-violet-600 p-2">
            <AppWindow className="h-5 w-5 text-white" />
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <h3 className="font-semibold text-violet-900">{title}</h3>
              <Sparkles className="h-4 w-4 text-violet-600" />
            </div>
            <p className="text-violet-700 text-sm">{purpose}</p>
          </div>
          <CheckCircle2 className="h-5 w-5 text-violet-600" />
        </div>
      </div>

      {/* Features */}
      <div className="border-b bg-white/50 p-4">
        <p className="mb-2 font-medium text-violet-900 text-sm">Core Features:</p>
        <div className="flex flex-wrap gap-2">
          {features.map((feature, index) => (
            <div
              className="rounded-full bg-violet-100 px-3 py-1 text-violet-700 text-xs font-medium"
              key={`feature-${index}`}
            >
              {feature}
            </div>
          ))}
        </div>
      </div>

      {/* Spec Version 2: React Code Preview */}
      {specVersion === 2 && reactCode && (
        <div className="border-b bg-white/50 p-4">
          <div className="mb-3 flex items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <Code2 className="h-4 w-4 text-violet-600" />
              <p className="font-medium text-violet-900 text-sm">React Component</p>
            </div>
            <button
              className={cn(
                "flex items-center gap-1.5 rounded px-2.5 py-1.5 text-xs font-medium transition-colors",
                copied
                  ? "bg-green-100 text-green-700"
                  : "bg-violet-100 text-violet-700 hover:bg-violet-200"
              )}
              onClick={handleCopyCode}
              type="button"
            >
              <Copy className="h-3 w-3" />
              {copied ? "Copied!" : "Copy Code"}
            </button>
          </div>

          {componentInfo && (
            <div className="mb-3 space-y-2 text-xs">
              <div className="flex gap-2">
                <span className="font-medium text-violet-700">Dependencies:</span>
                <span className="text-violet-600">
                  {Object.entries(componentInfo.dependencies)
                    .map(([pkg, version]) => `${pkg}@${version}`)
                    .join(", ")}
                </span>
              </div>
              <div className="flex gap-2">
                <span className="font-medium text-violet-700">Features:</span>
                <span className="text-violet-600">
                  {[
                    componentInfo.hasState && "State management",
                    componentInfo.hasEffects && "Side effects (useEffect)",
                  ]
                    .filter(Boolean)
                    .join(", ")}
                </span>
              </div>
            </div>
          )}

          <button
            className="w-full rounded border border-violet-200 bg-white py-2 text-xs font-medium text-violet-700 transition-colors hover:bg-violet-50"
            onClick={() => setShowCode(!showCode)}
            type="button"
          >
            {showCode ? "Hide" : "Show"} Code
          </button>

          {showCode && (
            <motion.div
              animate={{ opacity: 1, height: "auto" }}
              className="mt-3 overflow-hidden rounded bg-gray-900"
              exit={{ opacity: 0, height: 0 }}
              initial={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.2 }}
            >
              <pre className="max-h-96 overflow-auto p-3 text-xs text-gray-100">
                <code>{reactCode}</code>
              </pre>
            </motion.div>
          )}
        </div>
      )}

      {/* Legacy Version 1: Layout Structure */}
      {specVersion === 1 && layout && layout.length > 0 && (
        <div className="p-4">
          <p className="mb-3 font-medium text-violet-900 text-sm">
            Layout Structure:
          </p>
          <div className="space-y-2">
            {layout.map((item, index) => {
              const IconComponent = getIconForType(item.type);
              return (
                <div
                  className="flex items-start gap-3 rounded-lg border border-violet-200 bg-white p-3"
                  key={item.id || `layout-${index}`}
                >
                  <div className="h-4 w-4 flex-shrink-0 text-violet-600">
                    <IconComponent />
                  </div>
                  <div className="flex-1">
                    <p className="font-medium text-violet-900 text-xs uppercase tracking-wide">
                      {item.type}
                    </p>
                    <p className="mt-0.5 text-violet-700 text-sm">
                      {item.text || item.name || "Component"}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="border-t bg-violet-50/30 px-4 py-2">
        <p className="text-center text-violet-600 text-xs">
          {specVersion === 2
            ? `React Component v2 • ID: ${id.split("-")[0]}...`
            : `Mini-app spec v${specVersion} • ID: ${id.split("-")[0]}...`}
        </p>
      </div>
    </motion.div>
  );
}

// Helper function to get icon for layout item type
function getIconForType(type: string) {
  const iconClass = "h-4 w-4";

  switch (type) {
    case "header":
      return () => (
        <svg
          className={iconClass}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            d="M4 6h16M4 12h16m-7 6h7"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
          />
        </svg>
      );
    case "text":
      return () => (
        <svg
          className={iconClass}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            d="M4 6h16M4 12h10M4 18h16"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
          />
        </svg>
      );
    case "module":
      return () => (
        <svg
          className={iconClass}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
          />
        </svg>
      );
    default:
      return () => (
        <svg
          className={iconClass}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
          />
        </svg>
      );
  }
}
